### ISSUE TITLE
`datapackage.json` does not pass frictionless data default profile validation

### ISSUE THREAD

**Issue by DiegoPino** [webrecorder/wacz-format#57]
Hi,
When processing a WACZ file via frictionless data package library, it fails to load because some required  keys are missing

This is what I get when loading the .wacz via a library:

for this `wacz` 
```
  'resources' => 
  array (
    0 => 
    (object) array(
       'path' => 'indexes/index.cdx.gz',
       'stats' => 
      (object) array(
         'hash' => '946da153be52b106c29a493abb76c7ec0b4001f9ecfba8a971bba7550dea3d51',
         'bytes' => 13745,
      ),
       'hashing' => 'sha256',
    ),
    1 => 
    (object) array(
       'path' => 'indexes/index.idx',
       'stats' => 
      (object) array(
         'hash' => '1e5bad4bb5ef03ed276e82a7eb4c8cf1e17187b09a0e409894999009b84a0d2a',
         'bytes' => 211,
      ),
       'hashing' => 'sha256',
    ),
    2 => 
    (object) array(
       'path' => 'archive/sbr_54ec39079692c89cc5eb4823a8054eca_application-yt-2017-fixed-0a0b18b3-d15d-453d-87a1-4df8c5e129a8.warc',
       'stats' => 
      (object) array(
         'hash' => '61bbc2adcf2b04a39e673bad205d1161dfe762cbc368cc32b77890889476b633',
         'bytes' => 20601238,
      ),
       'hashing' => 'sha256',
    ),
    3 => 
    (object) array(
       'path' => 'pages/pages.jsonl',
       'stats' => 
      (object) array(
         'hash' => 'f003f1fc0501445f4090471ad994980fec986f7d486d573c549bd117ee0fea9a',
         'bytes' => 993,
      ),
       'hashing' => 'sha256',
    ),
  ),
   'metadata' => 
  (object) array(
     'title' => 'yt',
  ),
   'wacz_version' => '1.0.0',
)
```
I get this validation errors

```
NOTICE: PHP message: frictionlessdata\datapackage\Datapackages\DefaultDatapackage
NOTICE: PHP message: array (
  0 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[0].name] The property name is required',
  )),
  1 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[0].data] The property data is required',
  )),
  2 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[0]] Failed to match exactly one schema',
  )),
  3 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[1].name] The property name is required',
  )),
  4 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[1].data] The property data is required',
  )),
  5 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[1]] Failed to match exactly one schema',
  )),
  6 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[2].name] The property name is required',
  )),
  7 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[2].data] The property data is required',
  )),
  8 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[2]] Failed to match exactly one schema',
  )),
  9 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[3].name] The property name is required',
  )),
  10 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[3].data] The property data is required',
  )),
  11 => 
  frictionlessdata\datapackage\Validators\DatapackageValidationError::__set_state(array(
     'code' => 8,
     'extraDetails' => '[resources[3]] Failed to match exactly one schema',
  )),
)
```
Looking at the schema there are two required properties at the resource level that are not defined but one depends on the profile.
The one that is always required is `name`
https://github.com/frictionlessdata/specs/blob/6c7ccd2be7be435c7e7d798d6ec4882e3dfee163/schemas/dictionary/resource.yml#L6-L12 

`data` is modal and if the profile is set correctly?(more like a question) is not needed if `path` is present.
https://specs.frictionlessdata.io/data-resource/#data-location

Sadly the examples (minimal) in the docs are not clear but further down the MUST is well stated and the actual JSON schema used for validation is quite useful for that.

In the meantime since I'm processing only pages/pages.jsonl I will fix my code to not process WACZ files as frictionless data packages and just get the particular file but it would be great if the file would pass validation for version 1.2 to avoid exception processing for WACZ.

Thanks!

**Comment by ikreymer** [comment]
Thanks for catching this! Yes, the examples make this more complex than it should be, omitting the `name` property.
I wonder why the python tools didn't catch this either... The name would be easy to add, can just be derived from the path and is mostly redundant, but easy to do to remain compatible.

The `data` as I understand is only set if `path` is not, so the error also looks confusing since `path` is set, but hopefully adding `name` will fix the validation. Does adding name `name` to each resource fixe the validation errors?

Can definitely do a WACZ 1.1.1 update to add the `name` property. 

I suppose we should also considering a WACZ profile at some point, that may be a bigger task.

**Comment by DiegoPino** [comment]
@ikreymer thanks to you. Yes, i guess the only real mandatory one is name and the other errors are triggered because by not having name it does not comply with any profile and complains then in chains. For now this is not a big issue and I coded my way around it but for any future version having `name` would help a lot.

Big hugs
